# Generated by Django 3.1.2 on 2021-01-16 18:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
                ('annot_type', models.CharField(choices=[('ner', 'NER Annotation'), ('cls', 'Classification Annotation')], default='ner', max_length=10, verbose_name='Annotation Type')),
                ('nlp_model', models.CharField(max_length=100, verbose_name='NLP model Used for Annotation')),
                ('dataset', models.FileField(upload_to='', verbose_name='Input dataset')),
                ('output_data', models.FileField(null=True, upload_to=api.models.generate_user_file_path)),
            ],
        ),
    ]
