# Generated by Django 3.1.2 on 2021-01-16 19:04

import api.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='dataset',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='input_data',
            field=models.FileField(default='example.txt', upload_to=functools.partial(api.models.generate_user_file_path, *(), **{'type': 'input'})),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='output_data',
            field=models.FileField(null=True, upload_to=functools.partial(api.models.generate_user_file_path, *(), **{'type': 'output'})),
        ),
    ]
