# Generated by Django 3.1.2 on 2021-01-16 19:19

import api.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210116_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='input_data',
            field=models.FileField(blank=True, upload_to=functools.partial(api.models.generate_user_file_path, *(), **{'type': 'input'})),
        ),
    ]
