# Generated by Django 3.1.2 on 2021-01-17 19:43

import api.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210116_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='input_data',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(api.models.generate_user_file_path, *(), **{'type': 'input'})),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='output_data',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=functools.partial(api.models.generate_user_file_path, *(), **{'type': 'output'})),
        ),
        migrations.CreateModel(
            name='ReferenceEntitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectmodel')),
            ],
            options={
                'unique_together': {('name', 'project')},
            },
        ),
    ]
