# Generated by Django 3.1.2 on 2021-01-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210117_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceentitiesmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
