# Generated by Django 3.1.2 on 2021-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210117_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='nb_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='nb_regected',
            field=models.IntegerField(default=0),
        ),
    ]
